### ISSUE TITLE
ReadProcessMemory on Linux always fails

### ISSUE THREAD

**Issue by slxdy** [Reloaded-Project/Reloaded.Memory#4]
Here is my current code:
```cs
var mem = new ExternalMemory(Process.GetProcessesByName("tf_linux64").First());
var buffer = mem.ReadRaw((UIntPtr)0x7BE265A83BF8, 30);
Console.WriteLine(Encoding.ASCII.GetString(buffer));
```
The offset is definitely valid.

The output:
```
Unhandled exception. Reloaded.Memory.Exceptions.MemoryException: ReadProcessMemory failed to read 30 bytes of memory from 136212298349560. Error: 203
   at Reloaded.Memory.Exceptions.ThrowHelpers.ThrowReadExternalMemoryExceptionWindows(UIntPtr memoryAddress, Int32 structSize)
   at TfRpc.Program.Main(String[] args) in /home/slxdy/repos/TfRpc/TfRpc/Program.cs:line 14
```

Same result when ran as root.

**Comment by Sewer56** [comment]
That's certainly very strange.

Truth be told, when I originally wrote the code, I was still not daily driving Linux, I've only been daily driving since last year after a 5 year or so hiatus; so this was originally tested in CI. The tests do pass on my machine though, I'll test with a real process tomorrow when I get time.

In any case, I'll presume the following:

- You are reading from a valid memory address. (Not one shifted by ASLR or a dynamic pointer)
- Perms are obviously not the issue.

In any case, it's kind of strange. `errno: 203` is a very unusual value, I tried poking around, even looking some of the `errno.h` in the Linux source tree, and it doesn't seem to show up. (Maybe I just missed it).

Could it maybe be SELinux aswell? That might be worth checking.

In any case, I'm always down for a PR if there are better ways to do things. I just went with the POSIX API as I figured it would be widely supported among the nixes.

**Comment by slxdy** [comment]
I tried my own implementation of `process_vm_readv` and it seems to work fine. I will compare it to your source and see if anything is done wrong.

**Comment by slxdy** [comment]
Ah, i found the critical mistake. It's very hard to see at first, but check this out.
![image](https://github.com/user-attachments/assets/8a1df70a-ee6b-4cf9-b18b-cf66cc2a2f2d)
You mixed up the local and remote lov.
I will create a PR for this

**Comment by Sewer56** [comment]
Oh wow, that is a very simple one. Oh dearie me.

**Comment by Sewer56** [comment]
Looking at it from phone. It seems I put the parameters in the wrong order in the function signature, as the `_k32` suffix indicates that it was meant to emulate how kernel32's API worked.

**Comment by slxdy** [comment]
I figured. Tends to happen lol. The PR is up.

Also I gotta say, great project structure. Love it.
